"""The recommendation engine.

Every suggestion must answer three questions, in this order:

    1. What should the user do now?
    2. Why that, and not something else?
    3. What improvement will this likely create?

Candidates are generated by rules over measured analytics, given an urgency
between 0 and 100, then multiplied by whatever the feedback loop has learnt
about which kinds of advice this particular user acts on. Nothing here is
generative: the sentences are templates filled with real numbers, which is
exactly why they can be trusted.

The engine is deliberately conservative about claiming impact. Where a gain can
be computed from the readiness weights it is stated numerically; where it cannot,
it says what will change qualitatively instead of inventing a number.
"""

from datetime import date, timedelta

from . import content, feedback, readiness

# Rough index points per unit, derived from readiness.WEIGHTS. Used only to
# order suggestions and to phrase "worth about X" - never presented as precise.
COVERAGE_W = readiness.WEIGHTS["coverage"]
ACCURACY_W = readiness.WEIGHTS["accuracy"]
VOLUME_W = readiness.WEIGHTS["volume"]
CONSISTENCY_W = readiness.WEIGHTS["consistency"]


def _hash(route, **kw):
    return dict(route=route, **kw)


# ---------------------------------------------------------------------------
# candidate generators
# ---------------------------------------------------------------------------
def _revision(conn, bundle):
    debt = bundle.get("debt") or {}
    if not debt.get("overdue"):
        return None
    worst = debt.get("worst") or {}
    days = worst.get("days", 0)
    urgency = min(96, 42 + days * 3.5 + debt["overdue"] * 1.6)
    name = worst.get("name") or "your oldest topic"
    return dict(
        slug="revision",
        kind="revision",
        title="Revise %s first" % name,
        detail="%d item%s in the revision queue are past due; %s has been waiting "
        "%d day%s."
        % (
            debt["overdue"],
            "s" if debt["overdue"] != 1 else "",
            name,
            days,
            "s" if days != 1 else "",
        ),
        reason="Retention decays fastest just after a review falls due, so overdue "
        "material is the cheapest thing on the board to fix. New topics can "
        "wait a day; forgetting cannot be un-forgotten cheaply.",
        expected="Clearing the queue drops revision pressure from %d towards 0 and "
        "lifts the accuracy term as those topics stop leaking marks."
        % debt.get("pressure", 0),
        urgency=urgency,
        subject_slug=worst.get("subject", ""),
        topic_slug=worst.get("topic", ""),
        action=_hash("practice", mode="review"),
        action_label="Start revision set",
    )


def _accuracy_drop(conn, bundle):
    trends = bundle.get("trends") or []
    drops = [t for t in trends if t["direction"] == "down" and t["scope"] == "subject"]
    if not drops:
        drops = [t for t in trends if t["direction"] == "down"]
    if not drops:
        return None
    d = drops[0]
    label = d["slug"].replace("-", " ").title()
    return dict(
        slug="accuracy_drop",
        kind="accuracy",
        title="Accuracy in %s is sliding" % label,
        detail="%d%% correct in the last four weeks against %d%% in the four before "
        "that, over %d recent attempts." % (d["now"], d["before"], d["n_now"]),
        reason="A falling accuracy trend on ground you have already covered usually "
        "means half-learnt method rather than a new gap. It is worth more than "
        "opening a fresh topic, because the marks are already nearly yours.",
        expected="Recovering the earlier %d%% on this subject is worth roughly %.1f "
        "index points through the accuracy term."
        % (d["before"], (d["before"] - d["now"]) * ACCURACY_W / 100 * 3),
        urgency=min(92, 48 + abs(d["delta"]) * 1.5),
        subject_slug=d["slug"] if d["scope"] == "subject" else d.get("subject", ""),
        topic_slug=d["slug"] if d["scope"] == "topic" else "",
        action=_hash("practice", mode="weak"),
        action_label="Drill this subject",
    )


def _confidence_gap(conn, bundle):
    q = bundle.get("quality") or {}
    drift = q.get("confidence_drift")
    if drift is None or q.get("confidence_n", 0) < 12:
        return None
    if drift > 12:
        return dict(
            slug="overconfidence",
            kind="calibration",
            title="Your confidence is running ahead of your accuracy",
            detail="Across %d rated answers you felt about %d points surer than you "
            "actually were." % (q["confidence_n"], round(drift)),
            reason="Overconfidence is the failure mode that costs marks in the exam "
            "hall, because it stops you re-checking. A mixed set is the fastest "
            "way to recalibrate, since single-topic practice hides it.",
            expected="Closing the gap does not move the index directly, but it usually "
            "removes a chunk of the negative marking you are currently paying.",
            urgency=min(78, 40 + drift),
            action=_hash("practice", mode="mixed"),
            action_label="Take a mixed set",
        )
    if drift < -12:
        return dict(
            slug="underconfidence",
            kind="calibration",
            title="You are better than you think you are",
            detail="Across %d rated answers your accuracy beat your stated confidence "
            "by about %d points." % (q["confidence_n"], round(-drift)),
            reason="Under-confidence makes you skip questions you would have got right "
            "and over-revise things you already know. The fix is harder "
            "material, not more of the same.",
            expected="Attempting the questions you currently skip is the cheapest way "
            "to raise the accuracy sample and the estimated score.",
            urgency=52,
            action=_hash("practice", mode="boss"),
            action_label="Try a boss question",
        )
    return None


def _burnout(conn, bundle):
    """Long session plus falling accuracy inside the same day."""
    today = date.today().isoformat()
    rows = conn.execute(
        "SELECT correct FROM attempts WHERE day = ? ORDER BY id ASC", (today,)
    ).fetchall()
    mins = bundle.get("per_day", {}).get(today, 0)
    if len(rows) < 10 or mins < 150:
        return None
    half = len(rows) // 2
    early = sum(1 for r in rows[:half] if r["correct"]) / half * 100
    late = sum(1 for r in rows[half:] if r["correct"]) / (len(rows) - half) * 100
    if late >= early - 15:
        return None
    return dict(
        slug="burnout",
        kind="pacing",
        title="Take the pressure off for the rest of today",
        detail="Accuracy fell from %d%% in your first questions today to %d%% in the "
        "last ones, after %d minutes of study." % (round(early), round(late), mins),
        reason="A within-session accuracy collapse is a fatigue signal, not a knowledge "
        "signal. More hard questions now will mostly teach you the wrong lesson "
        "about your own ability.",
        expected="Switching to easier questions or notes protects the streak without "
        "logging attempts that will drag the accuracy term down.",
        urgency=88,
        action=_hash("practice", mode="speed"),
        action_label="Switch to easy questions",
    )


def _streak(conn, bundle):
    metrics = bundle["metrics"]
    today = date.today().isoformat()
    if bundle.get("per_day", {}).get(today):
        return None
    streak = metrics.get("current_streak", 0)
    if streak <= 0:
        if metrics.get("active_days", 0) == 0:
            return None
        return dict(
            slug="streak_restart",
            kind="consistency",
            title="Get one session on the board today",
            detail="The streak is at zero and the longest run so far was %d days."
            % metrics.get("longest_streak", 0),
            reason="Consistency is only 10%% of the index, but it is the term that "
            "drives every other term. A 25-minute session counts as a day.",
            expected="One logged session restarts the streak and keeps the calendar "
            "from developing another gap.",
            urgency=64,
            action=_hash("overview", action="log"),
            action_label="Log a short session",
        )
    return dict(
        slug="streak_rescue",
        kind="consistency",
        title="%d-day streak is unlogged today" % streak,
        detail="Nothing logged yet today. A %d-day run ends at midnight." % streak,
        reason="Rebuilding a streak from zero costs weeks; keeping this one costs "
        "twenty-five minutes. That is the whole argument.",
        expected="Holding the streak keeps the consistency term at %.0f/100 instead of "
        "letting it fall." % (bundle["metrics"].get("consistency_score", 0)),
        urgency=min(95, 55 + streak * 1.6),
        action=_hash("overview", action="log"),
        action_label="Log today's session",
    )


def _coverage(conn, bundle):
    health = bundle.get("topic_health") or []
    pending = [r for r in health if r["status"] == "pending"]
    if not pending:
        return None
    pending.sort(key=lambda r: (-r["marks"], -r["weight"]))
    p = pending[0]
    total_w = max(1, bundle["metrics"].get("topic_weight_total", 1))
    gain = p["weight"] / total_w * 100 * COVERAGE_W
    return dict(
        slug="coverage",
        kind="coverage",
        title="Open %s" % p["name"],
        detail="Untouched topic in %s (%d marks in the paper). %d topics still pending "
        "overall." % (p["subject_name"], p["marks"], len(pending)),
        reason="Coverage carries %d%% of the readiness index, more than any other term, "
        "and an untouched high-mark topic is the largest single lever left."
        % round(COVERAGE_W * 100),
        expected="Marking this done moves the index by roughly %.2f points, and puts "
        "the topic into the revision schedule so it stops being a blind spot." % gain,
        urgency=min(74, 30 + p["marks"] * 1.6 + p["weight"] * 2),
        subject_slug=p["subject"],
        topic_slug=p["topic"],
        action=_hash("subject", id=p["subject_id"]),
        action_label="Go to %s" % p["subject_name"],
    )


def _sample_size(conn, bundle):
    parts = readiness.components(bundle["metrics"])
    if parts["accuracy_confidence"] >= 100:
        return None
    attempted = bundle["metrics"].get("questions_attempted", 0)
    need = max(0, 150 - attempted)
    return dict(
        slug="sample",
        kind="accuracy",
        title="Build the accuracy sample",
        detail="%d questions attempted. The accuracy term is only %d%% confident and "
        "is being pulled toward neutral until about 150."
        % (attempted, parts["accuracy_confidence"]),
        reason="Right now the readiness index is understating you, not because you are "
        "weak but because it refuses to trust a small sample. That is honest, "
        "and the only fix is volume.",
        expected="About %d more questions unlocks the full accuracy term, currently "
        "worth up to %d index points." % (need, round(ACCURACY_W * 100)),
        urgency=48 if attempted else 70,
        action=_hash("practice", mode="mixed"),
        action_label="Practice now",
    )


def _mistake_pattern(conn, bundle):
    from . import quiz as quizmod

    br = quizmod.mistake_breakdown(conn)
    if br["tagged"] < 6 or not br["items"]:
        return None
    top = br["items"][0]
    if top["pct"] < 40:
        return None
    fixes = {
        "silly": (
            "Slow down on the arithmetic",
            "Silly slips are the cheapest marks on the table - no new theory "
            "needed, only a rewrite of your working habit.",
        ),
        "misread": (
            "Read the question twice before solving",
            "Misreads mean the knowledge is already there and the marks are "
            "being thrown away at the door.",
        ),
        "time": (
            "Pace is costing you more than knowledge",
            "Running out of time is a drill problem, not a syllabus problem.",
        ),
        "guess": (
            "Stop guessing on MCQs",
            "Every wrong MCQ guess costs a third of the marks. Skipping is "
            "often the higher-scoring choice.",
        ),
        "formula": (
            "Build a formula sheet",
            "Forgotten formulae are a retention problem, and a one-page sheet "
            "reviewed daily fixes it faster than more questions.",
        ),
        "concept": (
            "Go back to the concept, not more questions",
            "When the concept is the failure mode, extra practice just "
            "rehearses the misunderstanding.",
        ),
    }
    title, why = fixes.get(top["kind"], ("Look at your mistake pattern", ""))
    return dict(
        slug="mistakes",
        kind="mistakes",
        title=title,
        detail="%d%% of your tagged wrong answers are '%s' (%d of %d)."
        % (top["pct"], top["label"].lower(), top["n"], br["tagged"]),
        reason=why,
        expected="Cutting this one category in half would move overall accuracy by "
        "roughly %d points."
        % max(
            1,
            round(
                top["n"]
                / 2.0
                / max(1, bundle["metrics"].get("questions_attempted", 1))
                * 100
            ),
        ),
        urgency=44 + top["pct"] * 0.25,
        action=_hash("practice", mode="review"),
        action_label="Reattempt what you got wrong",
    )


def _velocity(conn, bundle):
    vel = bundle.get("velocity") or {}
    if vel.get("trend") != "falling" or not vel.get("prev7_per_day"):
        return None
    return dict(
        slug="velocity",
        kind="volume",
        title="Your weekly pace is dropping",
        detail="%d minutes a day over the last week against %d the week before."
        % (vel["last7_per_day"], vel["prev7_per_day"]),
        reason="The volume term rises slowly and cannot be sprinted at the end. A "
        "shrinking week is the earliest warning the plan is slipping, and the "
        "cheapest point to correct it.",
        expected="Returning to %d minutes a day keeps the volume term on its current "
        "trajectory rather than flattening." % vel["prev7_per_day"],
        urgency=40 + min(30, abs(vel.get("delta_per_day", 0)) * 0.6),
        action=_hash("overview", action="log"),
        action_label="Log a session",
    )


def _bank_gap(conn, bundle):
    stats = content.bank_stats()
    if stats["total"] and stats["topics_empty"] < 6:
        return None
    if not stats["total"]:
        return dict(
            slug="bank_empty",
            kind="content",
            title="The question bank is empty",
            detail="No usable questions found under content/questions or content/banks.",
            reason="Every adaptive feature in the app - the daily plan, the revision "
            "queue, the accuracy term - is downstream of the bank. Nothing else "
            "matters until there are questions.",
            expected="Import one paper and the daily plan, DPPs and revision schedule "
            "all start working.",
            urgency=99,
            action=_hash("practice", panel="bank"),
            action_label="See import instructions",
        )
    empty = stats["empty_topics"][:1]
    name = empty[0]["name"] if empty else "several topics"
    return dict(
        slug="bank_gap",
        kind="content",
        title="%d syllabus topics have no questions" % stats["topics_empty"],
        detail="Highest-weight gap: %s. Bank health is %d%% across %d questions."
        % (name, stats["health_pct"], stats["total"]),
        reason="The planner can only drill what exists. An empty topic looks strong on "
        "the heatmap purely because nothing has ever tested it, which is the one "
        "kind of blind spot this app is supposed to prevent.",
        expected="Importing a paper for these topics makes the weak-topic detector "
        "honest and widens DPP generation.",
        urgency=34,
        action=_hash("practice", panel="bank"),
        action_label="Open bank panel",
    )


def _plan_untouched(conn, bundle, plan):
    if not plan or not plan.get("blocks"):
        return None
    if plan.get("done_count"):
        return None
    first = plan["blocks"][0]
    return dict(
        slug="plan_start",
        kind="plan",
        title="Start today's plan: %s" % first["label"],
        detail="%d blocks, about %d minutes total. Nothing ticked off yet."
        % (len(plan["blocks"]), plan["total_minutes"]),
        reason=plan.get("reason", ""),
        expected="Completing the plan is the single action that moves coverage, "
        "accuracy and consistency in the same session.",
        urgency=58,
        action=_hash("overview", action="plan"),
        action_label="Open the plan",
        payload=dict(block=first["key"]),
    )


GENERATORS = (
    _burnout,
    _revision,
    _streak,
    _accuracy_drop,
    _confidence_gap,
    _coverage,
    _mistake_pattern,
    _sample_size,
    _velocity,
    _bank_gap,
)


# ---------------------------------------------------------------------------
# ranking
# ---------------------------------------------------------------------------
def build(conn, bundle, plan=None, limit=6, persist=True):
    """Generate, rank and persist today's recommendations."""
    cands = []
    for gen in GENERATORS:
        try:
            item = gen(conn, bundle)
        except Exception:
            item = None
        if item:
            cands.append(item)
    extra = _plan_untouched(conn, bundle, plan)
    if extra:
        cands.append(extra)

    for c in cands:
        base = float(c.get("urgency", 0))
        kind_w = feedback.kind_multiplier(conn, c["slug"])
        topic_w = (
            feedback.topic_multiplier(conn, c.get("topic_slug", ""))
            if c.get("topic_slug")
            else 1.0
        )
        c["urgency"] = round(base, 1)
        c["score"] = round(base * kind_w * (0.7 + 0.3 * topic_w), 2)
        c["learned_weight"] = round(kind_w, 3)
        c.setdefault("payload", {})
        c.setdefault("action_label", "Do it")
        c["band"] = (
            "now" if c["urgency"] >= 75 else "soon" if c["urgency"] >= 50 else "later"
        )

    cands.sort(key=lambda c: -c["score"])
    top = cands[:limit]
    if persist and top:
        try:
            feedback.mark_shown(conn, top)
        except Exception:
            pass
    return top


def next_best(conn, bundle, plan=None):
    """The single thing to put in the hero slot."""
    recs = build(conn, bundle, plan, limit=6)
    if not recs:
        return None
    best = dict(recs[0])
    others = recs[1:3]
    if others:
        best["instead_of"] = [
            dict(title=o["title"], slug=o["slug"], urgency=o["urgency"]) for o in others
        ]
        best["why_not"] = "Ranked above %s because urgency scores %.0f versus %.0f." % (
            others[0]["title"].lower(),
            best["urgency"],
            others[0]["urgency"],
        )
    return best


def ledger(conn, days=14):
    """What we suggested recently and what came of it."""
    since = (date.today() - timedelta(days=days)).isoformat()
    rows = conn.execute(
        "SELECT * FROM recommendations WHERE day >= ? ORDER BY day DESC, score DESC",
        (since,),
    ).fetchall()
    out = []
    for r in rows:
        out.append(
            dict(
                id=r["id"],
                day=r["day"],
                slug=r["slug"],
                title=r["title"],
                urgency=r["urgency"],
                score=r["score"],
                outcome=r["outcome"],
                acted=bool(r["acted_at"]),
                dismissed=bool(r["dismissed_at"]),
            )
        )
    return out
